### PR TITLE
Make tenacity version non-strict (compatible with other projects)

### PR DESCRIPTION
**Pull request by Anindyadeep**
> [!IMPORTANT]
> Loosen `tenacity` version constraint in `pyproject.toml` to `<=9.0.0` for compatibility with other projects.
> 
>   - **Dependencies**:
>     - Change `tenacity` version constraint in `pyproject.toml` from `9.0.0` to `<=9.0.0` to allow for more flexible version compatibility.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=getzep%2Fgraphiti&utm_source=github&utm_medium=referral)<sup> for 4299e9fc6e76bd576f83bb712156384c4dbdb771. It will automatically update as commits are pushed.</sup>

Actually the problem is, due to tenacity version being strict and not updated it was hard to integrate with other packages. So this PR tries to resolve that.

### CODE REVIEW

**Comment by Anindyadeep** [comment]
> 
> I have read the CLA Document and I hereby sign the CLA
>

**Comment by Anindyadeep** [comment]
recheck

**Comment by Anindyadeep** [comment]
recheck

**Comment by Anindyadeep** [comment]
Hi can we check this PR, it would be super helpful, it we can alter the version of tenacity, this would help us to remove all the merge conflicts we are facing while integrating graphiti. 

Thanks 

cc: @danielchalef @prasmussen15

**Comment by Anindyadeep** [comment]
Hi, with the latest release, the problem got solved, thank you, I am closing this PR.

**Comment by danielchalef** [comment]
@Anindyadeep glad we got this in! thanks for reporting the deps issue.

**Pull request closed without merging**
